name: Generate Release Keystore

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Generate Release Keystore
        run: |
          mkdir -p keystore

          keytool -genkeypair \
            -keystore keystore/release.keystore \
            -storepass android \
            -keypass android \
            -alias release \
            -keyalg RSA \
            -keysize 4096 \
            -validity 10000 \
            -dname "CN=HG,O=HG,C=IN"

      - name: Upload Keystore
        uses: actions/upload-artifact@v6
        with:
          name: release-keystore
          path: keystore/release.keystore